migrate:
  stage: migrate
  tags:
    - $ENVIRONMNENT
  needs: ['clear_cache']
  variables:
    OPTIONS: ''
  rules:
    - if: '$MIGRATE != "true"'
      when: never
    - if: '$MODE == "debug"'
      variables:
        OPTIONS: '--pretend'
    - when: on_success
  script:
    - cd /opt/$PROJECT_NAME
    - php artisan migrate:status
    - sudo php artisan migrate --force $OPTIONS
    - php artisan migrate:status
