rollback:
  stage: rollback
  tags:
    - $ENVIRONMNENT
  variables:
    OPTIONS: ''
  rules:
    - if: '$ROLLBACK != "true" || $CI_PIPELINE_SOURCE != "web"'
      when: never
    - if: '$MODE == "debug"'
      variables:
        OPTIONS: '--pretend'
  script:
    - cd /opt/$PROJECT_NAME
    - php artisan migrate:rollback --force $OPTIONS